name: testBuild Opencore

on:
  workflow_dispatch:
  release:

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1
  

jobs:
  build-opencore:
    name: build opencore
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
    - name: get tag
      if: github.event_name == 'release'
      run: cat ${{ github.ref }}
    
    - name: get lasttag
      if: github.event_name != 'release'
      run: echo not run from release  
      
