name: Build Opencore

on:
  workflow_dispatch:
  release:

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1
  

jobs:
  build-opencore:
    name: build opencore
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - name: get version
        if: github.event_name == 'release'
        run: |
          OPENCORE_VER=$(echo ${{ github.ref }} | sed "s/.*\/[^-]*-//g")
          echo "OPENCORE_VER=$OPENCORE_VER" >> $GITHUB_ENV
          
      - name: Clone Opencore Code
        uses: actions/checkout@v3
        with:
          repository: acidanthera/OpenCorePkg
          ref: ${{ env.OPENCORE_VER }}
     
      - name: change Opencore
        run: |
          sed -i .bak "s/L\"EFI\\\\\\\\OC\"/L\"EFI\\\\\\\\OC\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\"/g" Include/Acidanthera/Library/OcMainLib.h
          sed -i .bak "s/L\"OpenCore.efi\"/L\"OpenCore.efi\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\"/g" Include/Acidanthera/Library/OcMainLib.h
          sed -i .bak "s/L\"config.plist\"/L\"config.plist\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\\\\0\"/g" Include/Acidanthera/Library/OcMainLib.h      
          sed -i .bak "s/\\"OpenCore-\\${ver}-\\${2}.zip\\"/\\"OpenCore-\\${ver}-\\${2}(change_by_laozhiang).zip\\"/" build_oc.tool
      
      - name: check change Opencore
        run: |
          cat Include/Acidanthera/Library/OcMainLib.h
          cat build_oc.tool
    
      - name: Clone Opencore Code
        uses: actions/checkout@v3
        with:
          path: opencore-laozhiang


      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          path: opencore-laozhiang/README.md
          outputpath: opencore-laozhiang/ChangeOpenCore
    
      - run: cat opencore-laozhiang/ChangeOpenCore/README.html
